### PR TITLE
Bug Fixing and Refactoring

### LINKED ISSUE #121: Fix "Add to Cart"
Fix "Add to Cart" so that it displays flash error if user attempts to add amount to cart in excess of inventory

### PR DESCRIPTION
**Pull request by DanielEFrampton**
## Description
Resolves #121 
 - Admin users no longer see "Add to Cart" button
 - "Add to Cart" button no longer visible to any user when amount in cart is equal to inventory

Fixed instance variable collision causing current_user changing on user show page

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which maintains existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## RSpec Results
```
Finished in 12.23 seconds (files took 2.65 seconds to load)
233 examples, 0 failures

Coverage report generated for RSpec to /Users/dframpton/turing/2module/group_projec
ts/monster_shop_part_1/coverage. 2715 / 2715 LOC (100.0%) covered.
```

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ def cart
   end
 
   def current_user
-    @user ||= User.find(session[:user_id]) if session[:user_id]
+    user ||= User.find(session[:user_id]) if session[:user_id]
```
Comment (philjdelong) [inline app/controllers/application_controller.rb:11]: This was a real "RICH" one

**Review by philjdelong — APPROVED** [review]

**Review by KirbyDD — APPROVED** [review]

**Review by mel-rob — APPROVED** [review]
